version: "3.8"

services:
  db:
    container_name: mongo
    image: mongo
    restart: "always"
    env_file:
      - "config/mongo.env"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
    volumes:
      - "db:/data/db"
      - ./project/scripts/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
    command: mongod # Needed to invoke mongo-init.sh when the daemon starts

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  app:
    build: "project/"
    env_file:
      - "config/mongo.env"
      - "config/flask.env"
    expose:
      - "5000"
    volumes:
      - "./project:/usr/src/app"
    depends_on:
      - "db"
      - "kafka"

  server:
    image: "nginx:1.19-alpine"
    restart: "always"
    ports:
      - "80:80"
    volumes:
      - "./project/static:/srv"
      - "./config/nginx.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - "app"

volumes:
  db:
